# Generated by Django 5.1.3 on 2025-03-15 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('açıklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ana Kategori',
                'verbose_name_plural': 'Ana Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('açıklama', models.TextField(blank=True, null=True)),
                ('ana_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategoriler', to='categories.anakategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
                'constraints': [models.UniqueConstraint(fields=('ad', 'ana_kategori'), name='unique_kategori_ad_ana_kategori')],
            },
        ),
    ]
